### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by showarp** [pipe01/lcu-event-viewer#2]
How to run？

**Comment by pipe01** [comment]
Download [this](https://github.com/pipe01/lcu-event-viewer/releases/download/1.0/Events-1.0.zip) and unzip it, then run the .exe inside it

**Comment by showarp** [comment]
> 下载[这个](https://github.com/pipe01/lcu-event-viewer/releases/download/1.0/Events-1.0.zip)包并解压，然后运行里面的.exe文件
Thank you
